//
// Created by andrey on 14.04.2021.
//

#ifndef OPTIMIZATION_METHODS_GENTRATORQUADRATICFUNCTION_H
#define OPTIMIZATION_METHODS_GENTRATORQUADRATICFUNCTION_H

#endif //OPTIMIZATION_METHODS_GENTRATORQUADRATICFUNCTION_H
